version: '{build}'
os: Visual Studio 2015
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: RT/cjTB48AHLRy1Sd8Fk9mcTXt73td0QkrsOZRQ/dDcB8jAQQaluxzEsWJiQRhhq
install:
- ps: >-
    nuget update -self

    Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1" -OutFile ".\dotnet-install.ps1"

    $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetcli"

    & .\dotnet-install.ps1 -Channel "preview" -Version "1.0.0-preview3-003161" -InstallDir "$env:DOTNET_INSTALL_DIR"

build: off
test_script:
- ps: dotnet restore
- ps: ./Coverage.ps1
